### ISSUE TITLE
Obter Elemento

### ISSUE THREAD

**Issue by Pedropudin** [brenopelegrin/data-structures#2]
função pop aparentemente está funcionando mas não estou conseguindo imprimir os valores que são colocados na fila

**Comment by brenopelegrin** [comment]
Poderia dar um exemplo do erro que você tá encontrando?

O commit [3ea5fda](https://github.com/brenopelegrin/data-structures/commit/3ea5fda6224bdbfd90406acef1753f1619028b5e) resolve um typo na formatação do printList, tente dar um ``git pull`` e testar pra ver se resolve.

**Comment by brenopelegrin** [comment]
Fixed. It was a typo in lkdlist_getData, which was returning address instead of value.
