### ISSUE TITLE
Entrada de comando

### ISSUE THREAD

**Issue by Pedropudin** [brenopelegrin/data-structures#3]
Ao inserir um valor para command (operação a ser realizada) existem dois problemas:

1. Números muito grandes são interpretados como -1, apesar de não resultar em um erro leva o programa a imprimir as operações novamente (pois se encaixa no case -1)
2. Elementos que não sejam inteiros (double, string, etc) fazem o programa começar a rodar as instruções infinitas vezes

**Comment by brenopelegrin** [comment]
Solução:
1. Ao invés de ler um inteiro no comando, leia um char.

A 2 eu vou dar uma investigada aqui e depois te falo.

Em qua., 18 de out. de 2023 01:37, Pedro Martins Oliveira <
***@***.***> escreveu:

**Comment by brenopelegrin** [comment]
Pensando bem, acho que o problema não é tão relevante.

No caso dos comandos, o usuário não deveria colocar nenhum número muito grande pois está fora da lista de opções.

Como o projeto é uma fila de inteiros, o usuário deve saber que só pode inserir um inteiro e que um ``int`` tem um valor máximo (max = 2147483647).

Evidentemente seria bom resolver esses problemas para deixar o programa mais robusto e não suscetível a erros, mas como é só um projeto de graduação, acho que não tem problema.
